language: python
python: 3.5
env:
 - TOX_ENV=py27
 - TOX_ENV=py34
 - TOX_ENV=py35
 - TOX_ENV=lint
#before_install:
# - sudo apt-get install -y bzr git
install:
 - pip install tox
script:
 - tox -e $TOX_ENV

