language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - env: TOXENV=lint
    - env: TOXENV=lint-py2
    - env: TOXENV=docs
    - env: TOXENV=packaging
before_install: sudo apt-get install -y bzr git
install: pip install tox
script: tox
