language: python
python: 3.5
env:
 - TOX_ENV=py27
 - TOX_ENV=py34
 - TOX_ENV=py35
 - TOX_ENV=lint
# we need a valid git and bzr set up for the revision tests
before_install:
 - sudo apt-get install -y bzr git
 - git config --global user.email someone@somewhere.com
 - bzr whoami someone@somewhere.com
install:
 - pip install tox
script:
 - tox -e $TOX_ENV

